[package]
name = "midi2csv"
authors = ["Akiyuki Okayasu"]
version = "0.1.0"
edition = "2021"
rust-version = "1.67.1"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
midly = "0.5.3"
